describe('Watchlist Score Detail', () => {
  beforeEach(() => {
    cy.visitApp('/#/watchlist')
    cy.wait('@getWatchlist')
    cy.wait('@getWatchlistScores')
  })

  it('opens AI review detail without replacing the quant score', () => {
    cy.get('[data-testid="watchlist-review-score"]')
      .first()
      .find('[data-testid="watchlist-score-tag"]')
      .click()
    cy.get('[data-testid="watchlist-score-drawer"]').should('be.visible')
    cy.contains('AI 复核详情').should('be.visible')
    cy.contains('价格处于布林带中轨上方').should('be.visible')
    cy.get('[data-testid="watchlist-quant-score"]').first().should('contain', '56')
  })

  it('displays score rationale, confidence, source and timestamps', () => {
    cy.get('[data-testid="watchlist-review-score"]')
      .first()
      .find('[data-testid="watchlist-score-tag"]')
      .click()
    cy.get('[data-testid="watchlist-score-drawer"]').filter(':visible').within(() => {
      cy.contains('评分依据').should('be.visible')
      cy.contains('85%').should('be.visible')
      cy.contains('AI 复核').should('be.visible')
      cy.contains('生成：').should('be.visible')
      cy.contains('过期：').should('be.visible')
    })
  })

  it('closes the drawer', () => {
    cy.get('[data-testid="watchlist-review-score"]')
      .first()
      .find('[data-testid="watchlist-score-tag"]')
      .click()
    cy.get('[data-testid="watchlist-score-drawer"]').should('be.visible')
    cy.get('[data-testid="watchlist-score-drawer"]')
      .filter(':visible')
      .find('.el-drawer__close-btn')
      .click()
    cy.get('[data-testid="watchlist-score-drawer"]').should('not.be.visible')
  })

  it('keeps neutral fallback reviews out of the quant candidate tier', () => {
    cy.get('[data-testid="watchlist-table"] tbody tr')
      .contains('tr', 'AAPL.US')
      .within(() => {
        cy.get('[data-testid="watchlist-quant-score"]').should('not.exist')
        cy.get('[data-testid="watchlist-review-score"]')
          .should('contain', '50')
          .and('contain', '中性兜底')
          .and('contain', 'AI 降级结果')
          .and('not.contain', '优选')
      })
    cy.get('[data-testid="watchlist-score-filter"]').click()
    cy.get('.el-select__popper:visible')
      .contains('.el-select-dropdown__item', '量化优选')
      .click()
    cy.get('[data-testid="watchlist-table"]')
      .should('contain', 'NVDA.US')
      .and('not.contain', 'AAPL.US')
  })
})
