"""add llm interval fields to strategy_config

Revision ID: 20260602_add_llm_interval_fields
Revises: 41e077353669
Create Date: 2026-06-02 00:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260602_add_llm_interval_fields'
down_revision: Union[str, Sequence[str], None] = '41e077353669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_config', sa.Column('auto_interval_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('strategy_config', sa.Column('llm_suggested_buy_low', sa.Float(), nullable=True))
    op.add_column('strategy_config', sa.Column('llm_suggested_sell_high', sa.Float(), nullable=True))
    op.add_column('strategy_config', sa.Column('llm_confidence_score', sa.Float(), nullable=True))
    op.add_column('strategy_config', sa.Column('llm_analysis', sa.Text(), nullable=True))
    op.add_column('strategy_config', sa.Column('llm_last_analysis_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('strategy_config', sa.Column('llm_next_analysis_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('strategy_config', sa.Column('llm_applied_buy_low', sa.Float(), nullable=True))
    op.add_column('strategy_config', sa.Column('llm_applied_sell_high', sa.Float(), nullable=True))
    op.add_column('strategy_config', sa.Column('llm_applied_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('strategy_config', sa.Column('llm_reject_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_config', 'llm_reject_reason')
    op.drop_column('strategy_config', 'llm_applied_at')
    op.drop_column('strategy_config', 'llm_applied_sell_high')
    op.drop_column('strategy_config', 'llm_applied_buy_low')
    op.drop_column('strategy_config', 'llm_next_analysis_at')
    op.drop_column('strategy_config', 'llm_last_analysis_at')
    op.drop_column('strategy_config', 'llm_analysis')
    op.drop_column('strategy_config', 'llm_confidence_score')
    op.drop_column('strategy_config', 'llm_suggested_sell_high')
    op.drop_column('strategy_config', 'llm_suggested_buy_low')
    op.drop_column('strategy_config', 'auto_interval_enabled')
    # ### end Alembic commands ###
