"""Initial migration

Revision ID: 41e077353669
Revises: 
Create Date: 2026-05-17 18:41:06.978354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e077353669'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('longbridge_app_key', sa.Text(), nullable=False),
    sa.Column('longbridge_app_secret', sa.Text(), nullable=False),
    sa.Column('longbridge_access_token', sa.Text(), nullable=False),
    sa.Column('sct_key', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('executed_quantity', sa.Float(), nullable=True),
    sa.Column('executed_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runtime_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_state', sa.String(length=20), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=False),
    sa.Column('consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('last_trigger_price', sa.Float(), nullable=False),
    sa.Column('last_trigger_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('buy_low', sa.Float(), nullable=False),
    sa.Column('sell_high', sa.Float(), nullable=False),
    sa.Column('short_selling', sa.Boolean(), nullable=False),
    sa.Column('max_daily_loss', sa.Float(), nullable=False),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('sct_key', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_config')
    op.drop_table('runtime_state')
    op.drop_table('risk_events')
    op.drop_table('orders')
    op.drop_table('credential_config')
    # ### end Alembic commands ###
