"""Frozen, order-incapable quant-v6 research semantics."""

from typing import TYPE_CHECKING

from app.domain.watchlist_quant_v6.artifact import (
    MAX_QUANT_V6_ARTIFACT_COMPRESSED_BYTES,
    MAX_QUANT_V6_ARTIFACT_CONTAINER_ITEMS,
    MAX_QUANT_V6_ARTIFACT_INTEGER_ABS,
    MAX_QUANT_V6_ARTIFACT_JSON_DEPTH,
    MAX_QUANT_V6_ARTIFACT_JSON_NODES,
    MAX_QUANT_V6_ARTIFACT_KEY_BYTES,
    MAX_QUANT_V6_ARTIFACT_RAW_BYTES,
    MAX_QUANT_V6_ARTIFACT_STRING_BYTES,
    QUANT_V6_ARTIFACT_CODEC,
    QUANT_V6_ARTIFACT_COMPRESSION_LEVEL,
    QUANT_V6_ARTIFACT_SCHEMA_VERSION,
    QUANT_V6_ASSESSMENT_CONTRACT,
    QUANT_V6_ASSESSMENT_ARTIFACT_KIND,
    QUANT_V6_EVENT_CONTRACT,
    QUANT_V6_EVENT_ARTIFACT_KIND,
    QUANT_V6_PAYLOAD_SCHEMA_VERSION,
    QUANT_V6_SESSION_INPUT_CONTRACT,
    QUANT_V6_SESSION_INPUT_ARTIFACT_KIND,
    EncodedQuantV6Artifact,
    QuantV6ArtifactError,
    canonical_decimal,
    canonical_quant_v6_json,
    canonical_utc_timestamp,
    decode_quant_v6_artifact,
    encode_quant_v6_artifact,
    quant_v6_payload_sha256,
)
from app.domain.watchlist_quant_v6.assessment import (
    SESSION_COVERED,
    SESSION_MISSING,
    QuantV6Assessment,
    QuantV6AssessmentError,
    QuantV6SessionLeaf,
    assess_bar_next_open_stressed_window,
    session_cluster_one_sided_90_lcb,
)
from app.domain.watchlist_quant_v6.semantics import (
    BAR_NEXT_OPEN_STRESSED,
    QUANT_V6_ACQUISITION_ADJUSTMENT_MODE,
    QUANT_V6_ACQUISITION_CONTRACT_VERSION,
    QUANT_V6_ACQUISITION_PERIOD,
    QUANT_V6_ACQUISITION_SPEC,
    QUANT_V6_ACQUISITION_SPEC_DIGEST,
    QUANT_V6_ALGORITHM_VERSION,
    QUANT_V6_ASSESSMENT_SESSIONS,
    QUANT_V6_BAR_MINUTES,
    QUANT_V6_ENTRY_OFFSET_BARS,
    QUANT_V6_EXIT_OFFSET_BARS,
    QUANT_V6_FEE_RATE_BY_MARKET,
    QUANT_V6_HISTORICAL_STRESS_BPS_PER_SIDE,
    QUANT_V6_HOLDING_BARS,
    QUANT_V6_MIN_COVERED_SESSIONS,
    QUANT_V6_MIN_EDGE_COST_RATIO,
    QUANT_V6_MIN_EVENTS,
    QUANT_V6_MIN_EVENT_SESSIONS,
    QUANT_V6_REFERENCE_QUANTITY,
    QUANT_V6_SEMANTIC_DIGEST,
    QUANT_V6_SEMANTIC_SPEC,
    QUANT_V6_THRESHOLD_TRAINING_SESSIONS,
    SESSION_CLUSTER_T90_BY_DF,
    BarNextOpenStressedEvent,
    QuantV6Bar,
    QuantV6SemanticError,
    QuantV6ThresholdEvidence,
    QuantV6TrainingSession,
    build_bar_next_open_stressed_events,
    build_bar_next_open_stressed_session_events,
    build_quant_v6_threshold_evidence,
    quant_v6_consecutive_trading_session_dates,
    quant_v6_expected_rth_bar_starts,
    quant_v6_fee_rate,
    quant_v6_previous_trading_session_dates,
    quant_v6_session_bars_sha256,
    validate_bar_next_open_stressed_event,
    validate_quant_v6_threshold_evidence,
    validate_quant_v6_symbol_market,
)

if TYPE_CHECKING:
    from app.domain.watchlist_quant_v6.evaluator import (
        QUANT_V6_EVALUATOR_MANIFEST_VERSION,
        QUANT_V6_EVALUATOR_SOURCE_KEYS,
        quant_v6_evaluator_digest_sha256,
        quant_v6_evaluator_manifest,
    )


_EVALUATOR_EXPORT_NAMES = frozenset({
    "QUANT_V6_EVALUATOR_MANIFEST_VERSION",
    "QUANT_V6_EVALUATOR_SOURCE_KEYS",
    "quant_v6_evaluator_digest_sha256",
    "quant_v6_evaluator_manifest",
})


def __getattr__(name: str) -> object:
    """Load evaluator-only exports when a caller explicitly requests them."""
    if name not in _EVALUATOR_EXPORT_NAMES:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    from app.domain.watchlist_quant_v6 import evaluator as evaluator_module

    value = getattr(evaluator_module, name)
    globals()[name] = value
    return value


__all__ = [
    "BAR_NEXT_OPEN_STRESSED",
    "MAX_QUANT_V6_ARTIFACT_COMPRESSED_BYTES",
    "MAX_QUANT_V6_ARTIFACT_CONTAINER_ITEMS",
    "MAX_QUANT_V6_ARTIFACT_INTEGER_ABS",
    "MAX_QUANT_V6_ARTIFACT_JSON_DEPTH",
    "MAX_QUANT_V6_ARTIFACT_JSON_NODES",
    "MAX_QUANT_V6_ARTIFACT_KEY_BYTES",
    "MAX_QUANT_V6_ARTIFACT_RAW_BYTES",
    "MAX_QUANT_V6_ARTIFACT_STRING_BYTES",
    "QUANT_V6_ALGORITHM_VERSION",
    "QUANT_V6_ACQUISITION_ADJUSTMENT_MODE",
    "QUANT_V6_ACQUISITION_CONTRACT_VERSION",
    "QUANT_V6_ACQUISITION_PERIOD",
    "QUANT_V6_ACQUISITION_SPEC",
    "QUANT_V6_ACQUISITION_SPEC_DIGEST",
    "QUANT_V6_ARTIFACT_CODEC",
    "QUANT_V6_ARTIFACT_COMPRESSION_LEVEL",
    "QUANT_V6_ARTIFACT_SCHEMA_VERSION",
    "QUANT_V6_PAYLOAD_SCHEMA_VERSION",
    "QUANT_V6_ASSESSMENT_ARTIFACT_KIND",
    "QUANT_V6_ASSESSMENT_CONTRACT",
    "QUANT_V6_ASSESSMENT_SESSIONS",
    "QUANT_V6_BAR_MINUTES",
    "QUANT_V6_ENTRY_OFFSET_BARS",
    "QUANT_V6_EVALUATOR_MANIFEST_VERSION",
    "QUANT_V6_EVALUATOR_SOURCE_KEYS",
    "QUANT_V6_EVENT_ARTIFACT_KIND",
    "QUANT_V6_SESSION_INPUT_ARTIFACT_KIND",
    "QUANT_V6_EVENT_CONTRACT",
    "QUANT_V6_EXIT_OFFSET_BARS",
    "QUANT_V6_FEE_RATE_BY_MARKET",
    "QUANT_V6_HISTORICAL_STRESS_BPS_PER_SIDE",
    "QUANT_V6_HOLDING_BARS",
    "QUANT_V6_MIN_COVERED_SESSIONS",
    "QUANT_V6_MIN_EDGE_COST_RATIO",
    "QUANT_V6_MIN_EVENTS",
    "QUANT_V6_MIN_EVENT_SESSIONS",
    "QUANT_V6_REFERENCE_QUANTITY",
    "QUANT_V6_SEMANTIC_DIGEST",
    "QUANT_V6_SEMANTIC_SPEC",
    "QUANT_V6_THRESHOLD_TRAINING_SESSIONS",
    "QUANT_V6_SESSION_INPUT_CONTRACT",
    "SESSION_CLUSTER_T90_BY_DF",
    "SESSION_COVERED",
    "SESSION_MISSING",
    "BarNextOpenStressedEvent",
    "EncodedQuantV6Artifact",
    "QuantV6ArtifactError",
    "QuantV6Assessment",
    "QuantV6AssessmentError",
    "QuantV6Bar",
    "QuantV6SemanticError",
    "QuantV6SessionLeaf",
    "QuantV6ThresholdEvidence",
    "QuantV6TrainingSession",
    "assess_bar_next_open_stressed_window",
    "build_bar_next_open_stressed_events",
    "build_bar_next_open_stressed_session_events",
    "build_quant_v6_threshold_evidence",
    "canonical_decimal",
    "canonical_quant_v6_json",
    "canonical_utc_timestamp",
    "decode_quant_v6_artifact",
    "encode_quant_v6_artifact",
    "quant_v6_payload_sha256",
    "quant_v6_consecutive_trading_session_dates",
    "quant_v6_expected_rth_bar_starts",
    "quant_v6_evaluator_digest_sha256",
    "quant_v6_evaluator_manifest",
    "quant_v6_fee_rate",
    "quant_v6_previous_trading_session_dates",
    "quant_v6_session_bars_sha256",
    "session_cluster_one_sided_90_lcb",
    "validate_bar_next_open_stressed_event",
    "validate_quant_v6_threshold_evidence",
    "validate_quant_v6_symbol_market",
]
